name: Run Tests

# Workflow triggers
on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests targeting main

jobs:
  test:
    name: Run Pytest Tests on Matrix
    runs-on: ${{ matrix.os }}  # Use OS from the matrix

    # Define a testing matrix
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Test on Ubuntu, macOS, Windows
        python-version: ["3.10", "3.11", "3.12"]                # Test on Python 3.10, 3.11, 3.12

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python from matrix
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Use Python version from the matrix

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          # Upgrade the 'uv' tool
          python -m pip install --upgrade uv
          
          # Synchronize dependencies or perform additional setup
          uv sync
          
          # add dev dependencies
          uv add pytest


      # Step 4: Run pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=5 --disable-warnings -v